# Generated by Django 2.2.10 on 2021-10-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', max_length=1500, verbose_name='Описание')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата запуска опроса')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=1500, verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('text', 'Ответ текстом'), ('radio', 'Ответ с выбором одного варианта'), ('checkbox', 'Ответ с выбором нескольких вариантов')], default='text', max_length=20, verbose_name='Тип вопроса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100, verbose_name='Текст варианта ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='Вопрос')),
            ],
        ),
    ]
