# Generated by Django 2.2.10 on 2021-10-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
