# Generated by Django 2.2.10 on 2021-10-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20211016_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
